name: Requests for PHP
markdown: kramdown

kramdown:
    input: GFM
    hard_wrap: false
    use_coderay: true
    coderay:
        coderay_line_numbers: nil
        coderay_css: class

baseurl: /
exclude: ['buildtool.py', 'README.md', 'Vagrantfile', 'vagrant-provision.sh', 'Gemfile', 'Gemfile.lock']

gems:
  - jekyll-sitemap
