name: Requests for PHP
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    parse_block_html: false

baseurl: /
exclude: ['buildtool.py', 'README.md', 'Vagrantfile', 'vagrant-provision.sh', 'Gemfile', 'Gemfile.lock']

gems:
  - jekyll-sitemap
