name: Requests for PHP
markdown: kramdown
highlighter: rouge

# GH metadata: only needed to allow for local testing.
repository: "WordPress/Requests"

kramdown:
    input: GFM
    parse_block_html: false

baseurl: /
exclude: ['buildtool.py', 'README.md', 'Vagrantfile', 'vagrant-provision.sh', 'Gemfile', 'Gemfile.lock', '.jekyll-metadata']

plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
